#!/bin/sh
BRANCH_NAME=$(git symbolic-ref --short HEAD)

if [ "$BRANCH_NAME" = "main" ] || [ "$BRANCH_NAME" = "develop" ] || [ "$BRANCH_NAME" = "beta" ] then
  echo "Pushing to $BRANCH_NAME is not allowed."
  exit 1
fi
